### ISSUE TITLE
Create the grammars for the trees

### ISSUE THREAD

**Issue by josephking123** [josephking123/CSC3210_King_Forsyth_Huynh_Project4#4]
- [ ] Create three unique grammars. At least two of should are stochastic so that the trees they generate are unique.
- [ ] The stochastic trees should be obviously randomized.

**Comment by huynhwmc** [comment]
Here are some resources I found that may help with this, we can create one of the trees with the L-system grammar:
https://www.youtube.com/watch?v=3Mu0--aGfqg
https://www.youtube.com/watch?v=feNVBEPXAcE
https://codepen.io/mikkamikka/pen/DrdzVK
https://github.com/FrancescoGradi/L-System-Trees

I recommend creating a Tree object or class that stores the L-system parameters.
